import React from 'react'

const Day = () => {
    return (
        <div style={{ display: "flex" }}>
            <ul>
                <ol>02/14/23</ol>
                <ol>02/15/23</ol>
                <ol>02/16/23</ol>
                <ol>02/17/23</ol>
                <ol>02/18/23</ol>
                <ol>02/19/23</ol>
                <ol>02/20/23</ol>
                <ol>02/21/23</ol>
                <ol>02/22/23</ol>
                <ol>02/23/23</ol>
                <ol>02/24/23</ol>
                <ol>02/25/23</ol>
                <ol>02/26/23</ol>
                <ol>02/27/23</ol>
                <ol>02/28/23</ol>
                <ol>03/01/23</ol>
                <ol>03/02/23</ol>
                <ol>03/03/23</ol>
                <ol>03/08/23</ol>
                <ol>03/09/23</ol>
                <ol>03/10/23</ol>
                <ol>03/11/23</ol>
                <ol>03/12/23</ol>
                <ol>03/13/23</ol>
                <ol>03/14/23</ol>
                <ol>03/15/23</ol>
                <ol>03/16/23</ol>
                <ol>03/17/23</ol>
                <ol>03/18/23</ol>
                <ol>03/19/23</ol>
                <ol>03/20/23</ol>
                <ol>03/21/23</ol>
                <ol>03/23/23</ol>
                <ol>03/24/23</ol>
                <ol>03/25/23</ol>
                <ol>03/27/23</ol>
                <ol>03/29/23</ol>
                <ol>03/30/23</ol>
                <ol>03/31/23</ol>
                <ol>04/1/23</ol>
                <ol>04/2/23</ol>
                <ol>04/3/23</ol>
                <ol>04/4/23</ol>
                <ol>04/5/23</ol>
                <ol>04/6/23</ol>
                <ol>04/7/23</ol>
                <ol>04/8/23</ol>
                <ol>04/9/23</ol>
                <ol>04/10/23</ol>
                <ol>04/11/23</ol>
                <ol>04/12/23</ol>
                <ol>04/13/23</ol>
                <ol>04/14/23</ol>
                <ol>04/15/23</ol>
                <ol>04/16/23</ol>
                <ol>04/17/23</ol>
                <ol>04/18/23</ol>
                <ol>04/19/23</ol>
                <ol>04/20/23</ol>
                <ol>04/21/23</ol>
                <ol>04/22/23</ol>
                <ol>04/23/23</ol>
            </ul>
            <ul>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
                <ol>Inactivity</ol>
            </ul>
        </div>
    )
}

export default Day